# Generated by Django 4.1.3 on 2022-11-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=2048)),
                ('title', models.CharField(max_length=2048)),
                ('country', models.CharField(max_length=256)),
                ('keyword1', models.CharField(max_length=256)),
                ('keyword2', models.CharField(max_length=256)),
                ('label', models.CharField(max_length=64)),
            ],
        ),
    ]
