# Generated by Django 4.1.3 on 2022-11-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="source",
            field=models.CharField(max_length=2048, unique=True),
        ),
    ]
