# Generated by Django 4.1.3 on 2022-11-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_link_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="created_at",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="link",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
