# Generated by Django 4.1.3 on 2022-11-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_source_link_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="label",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
