# Generated by Django 4.1.3 on 2022-11-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_link_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="owner",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
