# Generated by Django 4.1.3 on 2022-11-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_link_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="label",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="owner",
            field=models.CharField(default="", max_length=64, null=True),
        ),
    ]
