# Generated by Django 4.1.3 on 2022-12-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_link_interesting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="interesting",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
